# Generated by Django 5.0.7 on 2024-08-05 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='client',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
