# Generated by Django 5.0.7 on 2024-08-05 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_alter_contact_phone_alter_portfolio_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='icon',
        ),
        migrations.AddField(
            model_name='service',
            name='img',
            field=models.ImageField(default=1, upload_to='service/'),
            preserve_default=False,
        ),
    ]
